name: flutter_news_toyapp
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  url_launcher: ^3.0.0
  built_collection: ^4.3.2
  built_value: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.4
  build: ^1.3.0
  source_gen: 0.9.7+1
  build_runner: ^1.10.1
  built_value_generator: ^7.1.0

flutter:
  uses-material-design: true
